-- MySQL Script generated by MySQL Workbench
-- Fri Oct 17 23:42:03 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema dineeasy_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dineeasy_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dineeasy_db` DEFAULT CHARACTER SET utf8mb3 ;
USE `dineeasy_db` ;

-- -----------------------------------------------------
-- Table `dineeasy_db`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dineeasy_db`.`customer` (
  `cust_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `contact_number` VARCHAR(20) NULL DEFAULT NULL,
  `address` TEXT NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`cust_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `dineeasy_db`.`menus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dineeasy_db`.`menus` (
  `menu_id` INT NOT NULL AUTO_INCREMENT,
  `item_name` VARCHAR(45) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  `availability` TINYINT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`menu_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `dineeasy_db`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dineeasy_db`.`orders` (
  `orders_id` INT NOT NULL AUTO_INCREMENT,
  `customer_id` INT NOT NULL,
  `status` ENUM('pending', 'confirmed', 'preparing', 'ready', 'delivering', 'delivered', 'cancelled') NOT NULL DEFAULT 'pending',
  `total_price` DECIMAL(10,2) NOT NULL DEFAULT '0.00',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`orders_id`),
  INDEX `customer_idx` (`customer_id` ASC) VISIBLE,
  CONSTRAINT `customer`
    FOREIGN KEY (`customer_id`)
    REFERENCES `dineeasy_db`.`customer` (`cust_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `dineeasy_db`.`order_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dineeasy_db`.`order_items` (
  `order_item_id` INT NOT NULL AUTO_INCREMENT,
  `order_id` INT NOT NULL,
  `quantity` INT NOT NULL,
  `subtotal` DECIMAL(10,2) NOT NULL,
  `menu_id` INT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`order_item_id`),
  INDEX `order_idx` (`order_id` ASC) VISIBLE,
  INDEX `menu_idx` (`menu_id` ASC) VISIBLE,
  CONSTRAINT `menu`
    FOREIGN KEY (`menu_id`)
    REFERENCES `dineeasy_db`.`menus` (`menu_id`),
  CONSTRAINT `order`
    FOREIGN KEY (`order_id`)
    REFERENCES `dineeasy_db`.`orders` (`orders_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
